### ISSUE TITLE
An open question of the ChatGPT generated code

### ISSUE THREAD

**Issue by Thompson-cyber** [rf20008/TheDiscordMathProblemBotRepo#20]
Hi, I found that the code [def infix_to_postfix](https://github.com/rf20008/TheDiscordMathProblemBotRepo/blob/15be7c5c8baf8d7cdc7fc773fe550407c1ce13a6/helpful_modules/problem_generator.py#L42) was generated by ChatGPT, with the comment ```# these are from ChatGPT```.

https://github.com/rf20008/TheDiscordMathProblemBotRepo/blob/15be7c5c8baf8d7cdc7fc773fe550407c1ce13a6/helpful_modules/problem_generator.py#L42-L81

My question is whether there may be a license issue with this code. I noticed that this code is very similar to [def calculate_expression](https://github.com/laketree2/BOJ_pythonex/blob/0883157c19824657f519588150ab839bc2bbcc0f/platinum/5/1287.py#L19) in the [laketree2/BOJ_pythonex](https://github.com/laketree2/BOJ_pythonex) repository.

- The ChatGPT-generated code was updated in Jul 2024, while the similar code was updated in 2023.

- [def infix_to_postfix](https://github.com/rf20008/TheDiscordMathProblemBotRepo/blob/15be7c5c8baf8d7cdc7fc773fe550407c1ce13a6/helpful_modules/problem_generator.py#L42)  is protected by the AGPL-3.0 license. However, the similar code is under a [No License](https://choosealicense.com/no-permission/) license. According to the conditions of this [No License](https://choosealicense.com/no-permission/) license:

>If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software.

How do you view potential license conflicts between ChatGPT-generated code and existing open-source code?

If a license violation exists, would you add some explanation regarding the ChatGPT-generated code?

Thank you for your attention to this matter. 😊

**Comment by rf20008** [comment]
Thank you so much for pointing this out!

I didn't do my research when I asked ChatGPT to create this problem, and I promise to try my best to see if other similar code already exists that I can't use.

**Comment by Thompson-cyber** [comment]
Thanks for your quickly reply. 👍
